<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Hello' => '',
    'Incorrect status' => '服务器繁忙！',
    'Back to message list' => '返回消息列表',
    'Click the SEND button to send the message' => '点击发送按钮发送该消息。',
    'Detail' => '详情',
    'Dialogue in {dialogue}' => '与 {dialogue} 对话',
    'Message' => '短消息',
    'Message Body' => '消息内容',
    'Message Inbox' => '收件箱',
    'Message content' => '消息内容',
    'My Message' => '我的消息',
    'My Message Inbox' => '收件箱',
    'New Message' => '新信息',
    'Please enter a user name' => '请输入一个用户名',
    'Please enter the message content' => '请输入消息内容',
    'Read' => '已读',
    'Reset' => '重置',
    'Send' => '发送',
    'Send Message' => '发送',
    'The requested page does not exist.' => '请求的页面不存在！',
    'Unread' => '未读',
    'User ID' => '用户ID',
    'Nickname' => '用户昵称',
    'You' => '你',
    'You enter the user name does not exist oh！' => '你输入的用户名不存在哦！',
    '{form} say to {to}' => '{form} 对 {to} 说',
];
